version: '3.8'

services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: bqm_postgres
    restart: always
    environment:
      POSTGRES_USER: queue_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: badminton_queue
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. The NestJS Backend
  backend:
    build: ./backend
    container_name: bqm_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Connects to the 'db' container defined above
      DATABASE_URL: postgresql://queue_admin:supersecretpassword@db:5432/badminton_queue?schema=public
    depends_on:
      - db
        command: >
      sh -c "npx prisma generate && 
             npx prisma db push --accept-data-loss && 
             npm run start:dev || tail -f /dev/null"

  # 3. The React Frontend
  frontend:
    build: ./frontend
    container_name: bqm_frontend
    restart: always
    ports:
      - "8080:80" # Maps NAS port 8080 to Nginx port 80
    depends_on:
      - backend

volumes:
  pgdata: # This ensures your database isn't deleted if the container restarts
